// mockData.js — Normalized types, expanded descriptions, rich mock data
// Serial Position Effect: strongest jobs (most detailed) at beginning

export const mockJobs = [
    {
        id: 1,
        title: 'Email Marketing Specialist',
        company: 'Revolut',
        company_logo: 'https://logo.clearbit.com/revolut.com',
        location: 'Madrid, Spain',
        category: 'Marketing',
        type: 'Full Time',
        description: 'Revolut is looking for an Email Marketing Specialist to help grow and engage our global customer base. You will design, execute, and optimize email campaigns across multiple markets, working closely with product and data teams. You\'ll use A/B testing, segmentation, and analytics to drive measurable results and ensure our communications are world-class.',
        tags: ['Marketing', 'Design'],
        created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 2,
        title: 'Brand Designer',
        company: 'Dropbox',
        company_logo: 'https://logo.clearbit.com/dropbox.com',
        location: 'San Francisco, US',
        category: 'Design',
        type: 'Full Time',
        description: 'Dropbox is seeking a talented Brand Designer to shape how the world perceives our product. You\'ll work within our design system to create visually compelling assets for campaigns, social media, and product features. You\'ll collaborate cross-functionally with marketing, product, and engineering teams to ensure design consistency across all touchpoints.',
        tags: ['Design', 'Business'],
        created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 3,
        title: 'Customer Success Manager',
        company: 'Pitch',
        company_logo: 'https://logo.clearbit.com/pitch.com',
        location: 'Berlin, Germany',
        category: 'Marketing',
        type: 'Full Time',
        description: 'Pitch is looking for a Customer Success Manager to champion our customers\' goals and ensure long-term retention. You\'ll onboard new users, deliver product training, resolve issues proactively, and surface insights to the product team. You\'re data-driven, empathetic, and love helping teams succeed with collaboration tools.',
        tags: ['Marketing'],
        created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 4,
        title: 'Visual Designer',
        company: 'Blinklist',
        company_logo: 'https://logo.clearbit.com/blinkist.com',
        location: 'Granada, Spain',
        category: 'Design',
        type: 'Full Time',
        description: 'Blinklist is looking for a Visual Designer to bring our reading experience to life. You\'ll design illustrations, icons, marketing materials, and UI components that resonate with millions of readers. Experience in motion design and 3D is a plus. You\'ll work in an agile environment with direct impact on the product\'s look and feel.',
        tags: ['Design'],
        created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 5,
        title: 'Product Designer',
        company: 'ClassPass',
        company_logo: 'https://logo.clearbit.com/classpass.com',
        location: 'Manchester, UK',
        category: 'Design',
        type: 'Full Time',
        description: 'ClassPass is seeking a Product Designer to improve the experience for millions of fitness enthusiasts. You\'ll lead end-to-end design for key product areas — from discovery and booking to user retention. You thrive on qualitative research, rapid prototyping, and iterating based on data. Experience designing for mobile apps is strongly preferred.',
        tags: ['Design', 'Marketing'],
        created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 6,
        title: 'Lead Designer',
        company: 'Canva',
        company_logo: 'https://logo.clearbit.com/canva.com',
        location: 'Ontario, Canada',
        category: 'Design',
        type: 'Full Time',
        description: 'Canva is looking for a Lead Designer to shape the future of visual communication tools. You\'ll mentor a team of designers, define design language, and drive strategic initiatives across product and brand. You bring a systems mindset, strong storytelling skills, and a passion for empowering creative professionals worldwide.',
        tags: ['Design', 'Business'],
        created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 7,
        title: 'Brand Strategist',
        company: 'GoDaddy',
        company_logo: 'https://logo.clearbit.com/godaddy.com',
        location: 'Marseille, France',
        category: 'Marketing',
        type: 'Full Time',
        description: 'GoDaddy is seeking a Brand Strategist to craft narratives that resonate with entrepreneurs and small business owners globally. You\'ll analyze market trends, define positioning, and collaborate with creative teams to bring campaigns to life. Excellent analytical thinking and presentation skills are required.',
        tags: ['Marketing'],
        created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 8,
        title: 'Data Analyst',
        company: 'Twitter',
        company_logo: 'https://logo.clearbit.com/x.com',
        location: 'San Diego, US',
        category: 'Technology',
        type: 'Full Time',
        description: 'Twitter is looking for a Data Analyst to transform complex datasets into actionable insights. You\'ll partner with product, engineering, and marketing teams to measure performance, identify trends, and influence decisions. Proficiency in SQL, Python, and data visualization tools (Tableau, Looker) is required.',
        tags: ['Technology'],
        created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 9,
        title: 'Social Media Manager',
        company: 'Nomad',
        company_logo: 'https://logo.clearbit.com/nomadhealth.com',
        location: 'Paris, France',
        category: 'Marketing',
        type: 'Full Time',
        description: 'Nomad is looking for a Social Media Manager to grow our community across Instagram, LinkedIn, and TikTok. You\'ll create engaging content calendars, manage communities, run paid campaigns, and analyze performance metrics. A creative eye and data-driven approach are essential to succeed in this role.',
        tags: ['Marketing', 'Design'],
        created_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 10,
        title: 'DevOps Engineer',
        company: 'Netlify',
        company_logo: 'https://logo.clearbit.com/netlify.com',
        location: 'Remote',
        category: 'Engineering',
        type: 'Remote',
        description: 'Netlify is looking for a DevOps Engineer to scale our deployment infrastructure serving millions of developers. You\'ll manage CI/CD pipelines, Kubernetes clusters, and observability tooling. You\'ll work closely with engineering teams to improve developer velocity and system reliability across globally distributed infrastructure.',
        tags: ['Engineering', 'Technology'],
        created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 11,
        title: 'Brand Designer',
        company: 'Maze',
        company_logo: 'https://logo.clearbit.com/maze.co',
        location: 'San Francisco, US',
        category: 'Design',
        type: 'Full Time',
        description: 'Maze is looking for a Brand Designer to evolve our visual identity as we scale from startup to category leader. You\'ll design landing pages, campaign materials, event assets, and brand guidelines. You have strong motion and illustration skills and are passionate about making complex products feel approachable.',
        tags: ['Marketing', 'Design'],
        created_at: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 12,
        title: 'Frontend Developer',
        company: 'Terraform',
        company_logo: 'https://logo.clearbit.com/hashicorp.com',
        location: 'Hamburg, Germany',
        category: 'Engineering',
        type: 'Full Time',
        description: 'Terraform Labs is looking for a Frontend Developer to build highly interactive web applications. You\'ll work closely with designers and backend engineers using React, TypeScript, and GraphQL. You care deeply about performance, accessibility, and delivering exceptional developer and user experiences.',
        tags: ['Engineering', 'Technology'],
        created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 13,
        title: 'Full Stack Developer',
        company: 'Udacity',
        company_logo: 'https://logo.clearbit.com/udacity.com',
        location: 'Remote',
        category: 'Technology',
        type: 'Remote',
        description: 'Udacity is seeking a Full Stack Developer to help build and scale our e-learning platform. You\'ll develop new features, improve system performance, and mentor junior engineers. You\'re proficient in Node.js, React, and PostgreSQL, and you thrive in an environment where you have end-to-end ownership of your features.',
        tags: ['Technology', 'Engineering'],
        created_at: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 14,
        title: 'HR Manager',
        company: 'Packer',
        company_logo: 'https://logo.clearbit.com/packer.io',
        location: 'Lucerne, Switzerland',
        category: 'Human Resource',
        type: 'Full Time',
        description: 'Packer is looking for an HR Manager to lead talent acquisition, performance management, and employee engagement initiatives. You\'ll build scalable hiring processes, manage HR systems, and partner with leadership on workforce planning. A background in fast-growing tech companies is strongly preferred.',
        tags: ['Human Resource', 'Business'],
        created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 15,
        title: 'People Operations Lead',
        company: 'Webflow',
        company_logo: 'https://logo.clearbit.com/webflow.com',
        location: 'Remote',
        category: 'Human Resource',
        type: 'Remote',
        description: 'Webflow is hiring a People Operations Lead to build world-class employee experiences across our fully remote team. You\'ll own onboarding, benefits, compensation benchmarking, and culture initiatives. You are empathetic, data-driven, and deeply committed to creating inclusive, equitable workplaces.',
        tags: ['Human Resource', 'Business'],
        created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    },
];

export const categories = [
    { name: 'Design', count: 235 },
    { name: 'Sales', count: 756 },
    { name: 'Marketing', count: 140 },
    { name: 'Finance', count: 325 },
    { name: 'Technology', count: 436 },
    { name: 'Engineering', count: 542 },
    { name: 'Business', count: 211 },
    { name: 'Human Resource', count: 346 },
];

export const locations = [
    'Remote',
    'New York, US',
    'San Francisco, US',
    'London, UK',
    'Berlin, Germany',
    'Paris, France',
    'Madrid, Spain',
    'Toronto, Canada',
];

/** Returns a human-friendly time-ago string (Doherty Threshold: instant feedback) */
export function timeAgo(dateStr) {
    const diff = Date.now() - new Date(dateStr).getTime();
    const days = Math.floor(diff / 86400000);
    if (days === 0) return 'Today';
    if (days === 1) return '1 day ago';
    if (days < 7) return `${days} days ago`;
    const weeks = Math.floor(days / 7);
    if (weeks === 1) return '1 week ago';
    if (weeks < 5) return `${weeks} weeks ago`;
    const months = Math.floor(days / 30);
    return months === 1 ? '1 month ago' : `${months} months ago`;
}
