// Fallback mock data for when backend is not running
export const mockJobs = [
    {
        id: 1,
        title: 'Email Marketing',
        company: 'Revolut',
        company_logo: 'https://ui-avatars.com/api/?name=R&background=000&color=fff&size=48&bold=true',
        location: 'Madrid, Spain',
        category: 'Marketing',
        type: 'Full Time',
        description: 'Revolut is looking for Email Marketing to help the team ma...',
        tags: ['Marketing', 'Design'],
        created_at: '2024-01-15T10:00:00Z',
    },
    {
        id: 2,
        title: 'Brand Designer',
        company: 'Dropbox',
        company_logo: 'https://logo.clearbit.com/dropbox.com',
        location: 'San Francisco, US',
        category: 'Design',
        type: 'Full Time',
        description: 'Dropbox is looking for Brand Designer to help the team...',
        tags: ['Design', 'Business'],
        created_at: '2024-01-14T10:00:00Z',
    },
    {
        id: 3,
        title: 'Email Marketing',
        company: 'Pitch',
        company_logo: 'https://ui-avatars.com/api/?name=Pitch&background=111&color=fff&size=48&bold=true',
        location: 'Berlin, Germany',
        category: 'Marketing',
        type: 'Full Time',
        description: 'Pitch is looking for Customer Manager to join marketing t...',
        tags: ['Marketing'],
        created_at: '2024-01-13T10:00:00Z',
    },
    {
        id: 4,
        title: 'Visual Designer',
        company: 'Blinklist',
        company_logo: 'https://ui-avatars.com/api/?name=B&background=00b89c&color=fff&size=48&bold=true',
        location: 'Granada, Spain',
        category: 'Design',
        type: 'Full Time',
        description: 'Blinkist is looking for Visual Designer to help team desi...',
        tags: ['Design'],
        created_at: '2024-01-12T10:00:00Z',
    },
    {
        id: 5,
        title: 'Product Designer',
        company: 'ClassPass',
        company_logo: 'https://ui-avatars.com/api/?name=CP&background=4640DE&color=fff&size=48&bold=true',
        location: 'Manchester, UK',
        category: 'Design',
        type: 'Full Time',
        description: 'ClassPass is looking for Product Designer to help us...',
        tags: ['Marketing', 'Design'],
        created_at: '2024-01-11T10:00:00Z',
    },
    {
        id: 6,
        title: 'Lead Designer',
        company: 'Canva',
        company_logo: 'https://logo.clearbit.com/canva.com',
        location: 'Ontario, Canada',
        category: 'Design',
        type: 'Full Time',
        description: 'Canva is looking for Lead Engineer to help develop n...',
        tags: ['Design', 'Business'],
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 7,
        title: 'Brand Strategist',
        company: 'GoDaddy',
        company_logo: 'https://ui-avatars.com/api/?name=G&background=1bdbdb&color=fff&size=48&bold=true',
        location: 'Marseille, France',
        category: 'Marketing',
        type: 'Full Time',
        description: 'GoDaddy is looking for Brand Strategist to join the team...',
        tags: ['Marketing'],
        created_at: '2024-01-09T10:00:00Z',
    },
    {
        id: 8,
        title: 'Data Analyst',
        company: 'Twitter',
        company_logo: 'https://ui-avatars.com/api/?name=T&background=1DA1F2&color=fff&size=48&bold=true',
        location: 'San Diego, US',
        category: 'Technology',
        type: 'Full Time',
        description: 'Twitter is looking for Data Analyst to help team desi...',
        tags: ['Technology'],
        created_at: '2024-01-08T10:00:00Z',
    },
    {
        id: 9,
        title: 'Social Media Assistant',
        company: 'Nomad',
        company_logo: 'https://ui-avatars.com/api/?name=N&background=36c48e&color=fff&size=48&bold=true',
        location: 'Paris, France',
        category: 'Marketing',
        type: 'Full-Time',
        description: 'Nomad is looking for Social Media Assistant to help grow their brand presence...',
        tags: ['Marketing', 'Design'],
        created_at: '2024-01-07T10:00:00Z',
    },
    {
        id: 10,
        title: 'Social Media Assistant',
        company: 'Netlify',
        company_logo: 'https://logo.clearbit.com/netlify.com',
        location: 'Paris, France',
        category: 'Marketing',
        type: 'Full-Time',
        description: 'Netlify is looking for Social Media Assistant to help grow their brand...',
        tags: ['Marketing', 'Design'],
        created_at: '2024-01-07T10:00:00Z',
    },
    {
        id: 11,
        title: 'Brand Designer',
        company: 'Maze',
        company_logo: 'https://ui-avatars.com/api/?name=M&background=4640DE&color=fff&size=48&bold=true',
        location: 'San Francisco, USA',
        category: 'Design',
        type: 'Full-Time',
        description: 'Maze is looking for Brand Designer to join their creative team...',
        tags: ['Marketing', 'Design'],
        created_at: '2024-01-06T10:00:00Z',
    },
    {
        id: 12,
        title: 'Interactive Developer',
        company: 'Terraform',
        company_logo: 'https://ui-avatars.com/api/?name=T&background=5c4ee5&color=fff&size=48&bold=true',
        location: 'Hamburg, Germany',
        category: 'Technology',
        type: 'Full-Time',
        description: 'Terraform is looking for Interactive Developer to build amazing experiences...',
        tags: ['Marketing', 'Design'],
        created_at: '2024-01-05T10:00:00Z',
    },
    {
        id: 13,
        title: 'Interactive Developer',
        company: 'Udacity',
        company_logo: 'https://ui-avatars.com/api/?name=U&background=26A4FF&color=fff&size=48&bold=true',
        location: 'Hamburg, Germany',
        category: 'Technology',
        type: 'Full-Time',
        description: 'Udacity is looking for Interactive Developer to help create e-learning tech...',
        tags: ['Marketing', 'Design'],
        created_at: '2024-01-04T10:00:00Z',
    },
    {
        id: 14,
        title: 'HR Manager',
        company: 'Packer',
        company_logo: 'https://ui-avatars.com/api/?name=P&background=FF6636&color=fff&size=48&bold=true',
        location: 'Lucern, Switzerland',
        category: 'Human Resource',
        type: 'Full-Time',
        description: 'Packer is looking for HR Manager to manage talent and recruitment...',
        tags: ['Marketing', 'Design'],
        created_at: '2024-01-03T10:00:00Z',
    },
    {
        id: 15,
        title: 'HR Manager',
        company: 'Webflow',
        company_logo: 'https://ui-avatars.com/api/?name=W&background=4353FF&color=fff&size=48&bold=true',
        location: 'Lucern, Switzerland',
        category: 'Human Resource',
        type: 'Full-Time',
        description: 'Webflow is looking for HR Manager to help scale the people team...',
        tags: ['Marketing', 'Design'],
        created_at: '2024-01-02T10:00:00Z',
    },
];

export const categories = [
    { name: 'Design', count: 235, icon: '✏️' },
    { name: 'Sales', count: 756, icon: '📊' },
    { name: 'Marketing', count: 140, icon: '📢' },
    { name: 'Finance', count: 325, icon: '📷' },
    { name: 'Technology', count: 436, icon: '🖥️' },
    { name: 'Engineering', count: 542, icon: '</>' },
    { name: 'Business', count: 211, icon: '💼' },
    { name: 'Human Resource', count: 346, icon: '👥' },
];

export const locations = [
    'Remote',
    'New York, US',
    'San Francisco, US',
    'London, UK',
    'Berlin, Germany',
    'Paris, France',
    'Madrid, Spain',
    'Toronto, Canada',
];
